#!/bin/bash
if [ $(uname) == Linux ] 
then
    gcc -O3 -Wall -fopenmp -g -D${1:-ALPHAVISCOSITY} migration_fast.c -lm -lgomp -lhdf5
else
    if [ $USER == zeus ]
    then
        INCFLAGS=-I/usr/local/include
        LIBFLAGS=-L/usr/local/lib
    fi
    gcc-4.9 -O3 -Wall -fopenmp -g $INCFLAGS -D${1:-ALPHAVISCOSITY}  migration_fast.c $LIBFLAGS -lgomp -lhdf5
fi
